// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpye9DOaXoD6pTUJfQG2F8YAhjJ-pilgA',
    appId: '1:963458548666:web:7755d9b3cfa594fafc5383',
    messagingSenderId: '963458548666',
    projectId: 'fir-memo-app-903ba',
    authDomain: 'fir-memo-app-903ba.firebaseapp.com',
    storageBucket: 'fir-memo-app-903ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAd0lfNUPzYaHJvg2uWrEhr-B-S3L6p4',
    appId: '1:963458548666:android:408ab568d8baab6cfc5383',
    messagingSenderId: '963458548666',
    projectId: 'fir-memo-app-903ba',
    storageBucket: 'fir-memo-app-903ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuL8jE6JR4wE_NMGx6HEcPt4yLkbwNj6E',
    appId: '1:963458548666:ios:bda9ded6d13e0b25fc5383',
    messagingSenderId: '963458548666',
    projectId: 'fir-memo-app-903ba',
    storageBucket: 'fir-memo-app-903ba.appspot.com',
    iosClientId: '963458548666-diohpg9b4s0seprpunq79v4451llivcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseUdemy1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuL8jE6JR4wE_NMGx6HEcPt4yLkbwNj6E',
    appId: '1:963458548666:ios:bda9ded6d13e0b25fc5383',
    messagingSenderId: '963458548666',
    projectId: 'fir-memo-app-903ba',
    storageBucket: 'fir-memo-app-903ba.appspot.com',
    iosClientId: '963458548666-diohpg9b4s0seprpunq79v4451llivcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseUdemy1',
  );
}
